<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgramsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $programs = [
        //clark
        ['name' => 'AT&T BB MULTI SERVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'EBAY BUY PHONE',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'EBAY BUY CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'EBAY SELL PHONE',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'EBAY SELL CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ZINUS',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'MODIVCARE FULL TIME',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST SPECIAL PROJECT',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'LUMEN/CRIS PHQ1',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ENS Q1',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'CRIS Q2A',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'CRIS Q2B',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'FIS',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'BRIGHTSPEED T1',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'BRIGHTSPEED 2A',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'BRIGHTSPEED ACQ',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST XM T1',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED 3P',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED BILLING',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST XM BILLING',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'HYOSUNG',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DOORDASH',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DUN & BRADSTREET',
        'description' => '',
        'program_group' => '',
        'site_id' => 1,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],

        //Quezon city
        ['name' => 'AT&T BB PTB MOB',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'BB LOYALTY',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T BB + TELCO SERVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MSS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'OCEAN X SALES PART TIME',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'OCEAN X SALES FULL TIME',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'OCEAN X CS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ALIEXPRESS EN',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ALIEXPRESS SOS1 (CHOICE STORE)',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ALIEXPRESS SOS2 (SERVICE STORE)',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T UV ESTABLISHED',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MSS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'OVERSTOCK VOICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'OVERSTOCK SMS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ROCKET CS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'PAYPAL CSIS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'PAYPAL APFS',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED X1(3P)',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED BILLING',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST WEST BI',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CENTRAL',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MOBILITY A',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MOBILITY B',
        'description' => '',
        'program_group' => '',
        'site_id' => 2,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        //BRIDGETOWNE
        ['name' => 'AT&T MOBILITY',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T UV ESTABLISHED',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'Westwood',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'MSI',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'LG - Order Entry(Email)',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'LG - Order Management(Email)',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'LG - Social Media',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'Pindoudou - TEMU',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ULTRA MINT - MOBILE',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ULTRA MINT - LIVE CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ULTRA MINT - VOICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 3,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        //Makati
                   ['name' => 'AT&T UV UBIZ',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T UV Established',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DTV DIRECT SALES',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DTV DIRECT SALES - CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T CONNECTED CAR',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DTV RECONNECTS',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DTV MOVERS',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'FOX NEWS',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DTV ILG',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ATT ACP',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ATT LEGACY',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ATT SAVES',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ATT NCCD',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ATT B2B',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MOBILITY B',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MOBILITY',
        'description' => '',
        'program_group' => '',
        'site_id' => 4,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],

        //MOA
                   ['name' => 'DTV VIDEO SERVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 5,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
                   ['name' => 'DTV VIDEO SERVICE FIBER',
        'description' => '',
        'program_group' => '',
        'site_id' => 5,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
                   ['name' => 'AT&T MTS',
        'description' => '',
        'program_group' => '',
        'site_id' => 5,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
                   ['name' => 'ATT TRIAGE',
        'description' => '',
        'program_group' => '',
        'site_id' => 5,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
                   ['name' => 'AT&T MOBILITY',
        'description' => '',
        'program_group' => '',
        'site_id' => 5,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        //SM Davao
                   ['name' => 'AT&T BB TELCO SERVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T BB PTB MOB',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'DTV VIDEO SERVICE DV',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MTS',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'Q5',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'LEGAL ZOOM VOICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'LEGAL ZOOM CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 6,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],

        //SM Robinson
                   ['name' => 'SXM SERVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'SXM SAVES',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'NOTION',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MOBILITY CLG',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'MODIVCARE ',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ULTRAMINT ',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ULTRAMINT LIVECHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 7,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],

        //davao Delta
                   ['name' => 'DTV TECH - VIDEO TECH',
        'description' => '',
        'program_group' => '',
        'site_id' => 8,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'GREAT JONES',
        'description' => '',
        'program_group' => '',
        'site_id' => 8,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'AT&T MSS',
        'description' => '',
        'program_group' => '',
        'site_id' => 8,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'FACEBOOK META',
        'description' => '',
        'program_group' => '',
        'site_id' => 8,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'PAYPAL APFS',
        'description' => '',
        'program_group' => '',
        'site_id' => 8,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'PAYPAL CS',
        'description' => '',
        'program_group' => '',
        'site_id' => 8,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],

        //central Davao
                   ['name' => 'COMCAST NED 3P',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED BILLING',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN BULK',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN SMB/B2B',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN 3P REPAIR',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN  XM CBM',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NAT XM T1',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NAT XM T2',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED eCHAT REPAIR',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED SMB',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST SMB MOBILE ACTIVATIONS',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN SMB BSC',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST WEST SMB BSC',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST NED SMB BSC',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST DIGITAL CARE',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN MIDMARKET OVN',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'COMCAST CEN MIDMARKET BILLING',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'SHOPHQ IB SALES',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'SHOPHQ SERVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'HERTZ REX',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'HERTZ RES',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ROKU CARE',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ROKU DEVICE',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'MODIVCARE',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'ILG TAGALOG',
        'description' => '',
        'program_group' => '',
        'site_id' => 9,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],

        //DFC
        ['name' => 'MICROSOFT TS CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 10,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'MICROSOFT CS CHAT',
        'description' => '',
        'program_group' => '',
        'site_id' => 10,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'XBOX',
        'description' => '',
        'program_group' => '',
        'site_id' => 10,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'FIS SNAP',
        'description' => '',
        'program_group' => '',
        'site_id' => 10,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'META TECH T1',
        'description' => '',
        'program_group' => '',
        'site_id' => 10,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ['name' => 'META SOCIAL',
        'description' => '',
        'program_group' => '',
        'site_id' => 10,
        'created_by' => 1,
        'updated_by' => null,
        'is_active' => 1,
        ],
        ];

        DB::table('programs')->insert($programs);
    }
}
