<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;

class EmployeeExport implements FromCollection, WithHeadings, ShouldAutoSize
{
    protected $data;

    public function __construct(array $data)
    {
        $this->data = collect($data);
    }

    public function collection()
    {
        return $this->data;
    }

    public function headings(): array
    {
        return [
            "EMPLOYEE ID",
            "LAST NAME",
            "FIRST NAME",
            "MIDDLE NAME",
            "EMAIL ADDRESS",
            "CONTACT NUMBER",
            "DATE OF BIRTH",
            "HIRE MONTH",
            "HIRE DATE",
            "POSITION",
            "EMPLOYEE STATUS",
            "JO STATUS",
            "EMPLOYEE ADDED BY",
            "EMPLOYEE CREATED AT",
            "EMPLOYEE UPDATED BY",
            "EMPLOYEE UPDATED AT",
            "REGION",
            "SITE",
            "LOB",
            "TEAM NAME",
            "PROJECT CODE",
            "UPDATED AT",
            "NBI FINAL STATUS",
            "NBI VALIDITY DATE",
            "NBI SUBMITTED DATE",
            "NBI PRINTED DATE",
            "NBI REMARKS",
            "NBI",
            "NBI LAST UPDATED AT",
            "NBI UPDATED BY",
            "DT FINAL STATUS",
            "DT RESULTS DATE",
            "DT TRANSACTION DATE",
            "DT ENDORSEMENT DATE",
            "DT REMARKS",
            "DT",
            "DT LAST UPDATED AT",
            "DT UPDATED BY",
            "PEME",
            "PEME REMARKS",
            "PEME ENDORSEMENT DATE",
            "PEME RESULTS DATE",
            "PEME TRANSACTION DATE",
            "PEME FINAL STATUS",
            "PEME LAST UPDATED AT",
            "PEME UPDATED BY",
            "PROOF OF SSS SUBMITTED",
            "SSS FINAL STATUS",
            "SSS SUBMITTED DATE",
            "SSS REMARKS",
            "SSS NUMBER",
            "SSS",
            "SSS LAST UPDATED AT",
            "SSS UPDATED BY",
            "PHIC SUBMITTED DATE",
            "PHIC FINAL STATUS",
            "PROOF OF PHIC SUBMITTED",
            "PHIC REMARKS",
            "PHIC NUMBER",
            "PHIC",
            "PHIC LAST UPDATED AT",
            "PHIC UPDATED BY",
            "HDMF SUBMITTED DATE",
            "HDMF FINAL STATUS",
            "PROOF OF HDMF SUBMITTED",
            "HDMF REMARKS",
            "HDMF NUMBER",
            "HDMF",
            "HDMF LAST UPDATED AT",
            "HDMF UPDATED BY",
            "TIN SUBMITTED DATE",
            "TIN FINAL STATUS",
            "PROOF OF TIN SUBMITTED",
            "TIN REMARKS",
            "TIN NUMBER",
            "TIN",
            "TIN LAST UPDATED AT",
            "TIN UPDATED BY",
            "HEALTH CERTIFICATE VALIDITY DATE",
            "HEALTH CERTIFICATE SUBMITTED DATE",
            "HEALTH CERTIFICATE REMARKS",
            "HEALTH CERTIFICATE",
            "HEALTH CERTIFICATE FINAL STATUS",
            "HEALTH CERTIFICATE LAST UPDATED AT",
            "HEALTH CERTIFICATE UPDATED BY",
            "OCCUPATIONAL PERMIT VALIDITY DATE",
            "OCCUPATIONAL PERMIT SUBMITTED DATE",
            "OCCUPATIONAL PERMIT REMARKS",
            "OCCUPATIONAL PERMIT",
            "OCCUPATIONAL PERMIT FINAL STATUS",
            "OCCUPATIONAL PERMIT LAST UPDATED AT",
            "OCCUPATIONAL PERMIT UPDATED BY",
            "OFAC CHECKED DATE",
            "OFAC FINAL STATUS",
            "OFAC REMARKS",
            "OFAC",
            "OFAC LAST UPDATED AT",
            "OFAC UPDATED BY",
            "SAM CHECKED DATE",
            "SAM FINAL STATUS",
            "SAM REMARKS",
            "SAM",
            "SAM LAST UPDATED AT",
            "SAM UPDATED BY",
            "OIG CHECKED DATE",
            "OIG FINAL STATUS",
            "OIG REMARKS",
            "OIG",
            "OIG LAST UPDATED AT",
            "OIG UPDATED BY",
            "CIBI CHECKED DATE",
            "CIBI FINAL STATUS",
            "CIBI REMARKS",
            "CIBI",
            "CIBI LAST UPDATED AT",
            "CIBI UPDATED BY",
            "BGC ENDORSEMENT DATE",
            "BGC RESULTS DATE",
            "BGC FINAL STATUS",
            "BGC REMARKS",
            "BGC",
            "BGC LAST UPDATED AT",
            "BGC UPDATED BY",
            "BIRTH CERTIFICATE",
            "BIRTH CERTIFICATE SUBMITTED DATE",
            "PROOF OF BIRTH CERTIFICATE",
            "BIRTH CERTIFICATE REMARKS",
            "BIRTH CERTIFICATE LAST UPDATED AT",
            "BIRTH CERTIFICATE UPDATED BY",
            "DEPENDENT'S BIRTH CERTIFICATE",
            "DEPENDENT'S BIRTH CERTIFICATE SUBMITTED DATE",
            "PROOF OF DEPENDENT'S BIRTH CERTIFICATE",
            "DEPENDENT'S BIRTH CERTIFICATE REMARKS",
            "DEPENDENT'S BIRTH CERTIFICATE LAST UPDATED AT",
            "DEPENDENT'S BIRTH CERTIFICATE UPDATED BY",
            "MARRIAGE CERTIFICATE",
            "MARRIAGE CERTIFICATE SUBMITTED DATE",
            "PROOF OF MARRIAGE CERTIFICATE",
            "MARRIAGE CERTIFICATE REMARKS",
            "MARRIAGE CERTIFICATE LAST UPDATED AT",
            "MARRIAGE CERTIFICATE UPDATED BY",
            "SCHOLASTIC RECORD",
            "SCHOLASTIC RECORD SUBMITTED DATE",
            "PROOF OF SCHOLASTIC RECORD",
            "SCHOLASTIC RECORD REMARKS",
            "SCHOLASTIC RECORD LAST UPDATED AT",
            "SCHOLASTIC RECORD UPDATED BY",
            "PREVIOUS EMPLOYMENT",
            "PREVIOUS EMPLOYMENT SUBMITTED DATE",
            "PROOF OF PREVIOUS EMPLOYMENT",
            "PREVIOUS EMPLOYMENT REMARKS",
            "PREVIOUS EMPLOYMENT LAST UPDATED AT",
            "PREVIOUS EMPLOYMENT UPDATED BY",
            "SUPPORTING DOCUMENT",
            "SUPPORTING DOCUMENT SUBMITTED DATE",
            "PROOF OF SUPPORTING DOCUMENT",
            "SUPPORTING DOCUMENT REMARKS",
            "SUPPORTING DOCUMENT LAST UPDATED AT",
            "SUPPORTING DOCUMENT UPDATED BY",
        ];
    }
}
